spring:
  application:
    name: jpa
  datasource:
    url: jdbc:mysql://localhost:3308/crm_app
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
jwt:
  key: pYL/bFa3qdmZC52COcG3UO/Xd+vjJgpo42ucD7WRJRQ=